
### The University of Melbourne, School of Computing and Information Systems
# COMP30027 Machine Learning, 2021 Semester 1

## Week 2 - Introduction

Welcome to Jupyter Notebook—an interactive environment that mixes code, visualisations and text.

Jupyter Notebook supports many programming languages (called "kernels" in the Jupyter lingo). In this course, we'll mainly be using Python 3 due to its popularity in the machine learning/data science communities. Information about the kernel is diplayed in the top right of the UI.

## Cells

Notebooks are made up cells: *markdown cells* and *code cells*. 
This cell is an example of a markdown cell. 
Markdown cells can contain text, tables, images, equations, etc. 
(see the Markdown guide under the _Help_ menu for more info). 

You can edit a markdown cell by double-clicking on it. To convert cells to markdown, highlight the cell and hit `<M>`. To convert back to a code cell, hit `<Y>`.

To evaluate the cell press the <button class='btn btn-default btn-xs'><i class="icon-step-forward fa fa-step-forward"></i></button> button in the toolbar, or hit `<CTRL>+<ENTER>`. 
Try it below! 

--- **Edit me** ---

Next are some code cells. 
You can evaluate them individually, using the <button class='btn btn-default btn-xs'><i class="icon-step-forward fa fa-step-forward"></i></button> button or by hitting `<CTRL>+<ENTER>`. 
Often, you'll want to run all cells in the notebook, or below a certain point. The functions for doing this are in the _Cell_ menu.

In [2]:
message = "Hello world!"

In [3]:
print(message)

Hello world!


Please ensure that the scipy, numpy, matplotlib, and sklearn packages are installed (although we won’t be
using the latter two today).

In [4]:
import scipy
import numpy as np 
import matplotlib as mpl
import sklearn

(You might wish to examine the installation instructions at http://scipy.org/install.html
if you are considering using your local machine.)

## NumPy Basics

The main numpy object is a so-called “homogeneous multidimensional array” — note that this is a little less flexible than using a list or tuple, but it allows mathematical operations to be performed much faster. (And we’ll be doing a fair bit of number-crunching this semester, so this is an important property.) The following is an introduction to NumPy functions and properties.

### Creating Arrays

In [5]:
a = np.array([0, 1, 2, 3, 4])
b = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]], dtype = float)
c = np.array([[1, 6], [2, 7], [3, 8], [4, 9], [5, 10]], dtype = int)

In [6]:
np.arange(0, 10)     # array of evenly spaced values

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.zeros((2, 3))     # array of zeros with the given shape

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [8]:
np.ones(2)           # array of ones with the given shape

array([ 1.,  1.])

In [9]:
np.empty((2, 3))     # empty array (arbitrary values)

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [10]:
np.full((2, 3), 3)   # fill new array with given shape

array([[3, 3, 3],
       [3, 3, 3]])

### Inspecting an array

In [15]:
b.size               # number of elements in the array

10

In [12]:
b.ndim               # number of dimensions

2

In [13]:
b.shape              # lengths of each dimension

(2, 5)

In [14]:
b.dtype              # data type of array elements

dtype('float64')

### Numpy Basic operations


Numpy supports vector (and matrix) operations,like addition, subtraction, and scalar multiplication.

You need to be very, very careful about manipulating arrays of different sizes. numpy typically won’t throw exceptions. Instead, it will do "something": that something might be very intelligent, like automatically increasing the dimensionality of the smaller array to match the larger array — but if you aren’t expecting it, the errors can be very difficult to find.

In [16]:
a1 = np.array([0,1,2,3,4])
a2 = np.array([1,3,-2,0,4])

In [17]:
print(a1 + a2)                # element-wise addition (or np.add)

[1 4 0 3 8]


In [18]:
print(a1 - a2)                # element-wise subtraction (or np.subtract)

[-1 -2  4  3  0]


In [19]:
print(a1 * a2)                # element-wise multiplication (or np.multiply)

[ 0  3 -4  0 16]


In [20]:
print(a1 / a2)                # element-wise division (or np.divide)

[ 0.          0.33333333 -1.                 inf  1.        ]


/Users/hasti.samadi/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


In [21]:
b.sum()              # sum elements

45.0

In [22]:
b.min()              # minimum element

0.0

In [23]:
b.max()              # maximum element

9.0

In [24]:
b.mean()             # mean of elements

4.5

In [25]:
a == a              # element-wise comparison

array([ True,  True,  True,  True,  True], dtype=bool)

#### Question 1
How can we add (element-wise) arrays `b` and `c`? 

#### Answer
We cannot! ;) The two arrays `b` and `c` have different shapes. `b.shape` is `(2, 5)`, while `c.shape` is `(5,2)` so none of the basic numpy operations (addition, subtraction, and scalar multiplication) can happen between them.   

In [26]:
b + c          # ValueError: operands could not be broadcast together with shapes (2,5) (5,2) 

ValueError: operands could not be broadcast together with shapes (2,5) (5,2) 

#### Question 2
What do you think would be the result of comparision `b < 2`? How about `a1 = a2`?

In [27]:
b < 2                   # element-wise comparison

array([[ True,  True, False, False, False],
       [False, False, False, False, False]], dtype=bool)

In [28]:
a1 == a2                # element-wise comparison

array([False, False, False, False,  True], dtype=bool)

#### Question 3
How can we check whether arrays have the same shape and elements?

In [29]:
np.array_equal(a, b)  # check whether arrays have the same shape and elements

False

### Using Numpy arrays

Numpy arrays can be indexed, sliced, and iterated over, similarly to lists. 

#### Exercise 1
Write a function to calculate the **Euclidean distance** between $\vec{a}$ and $\vec{b}$. Use this function to calculate the eculadian Distance between `a1` and `a2`.

In [30]:
def my_euclidean_dist(a, b):
    assert len(a)==len(b), "Arrays are of different sizes!"
    s = 0
    return np.sqrt(sum([(a[i]-b[i])*(a[i]-b[i]) for i in range(len(a))]))

In [31]:
print(my_euclidean_dist(a1, a2))

5.47722557505


### Numpy and Matrices

Matrices can be made in numpy by wrapping a list of lists. For example the matrices M and N can be modeled in Numpy by using the following code.

\begin{align}
    \mathbf{M} = \begin{pmatrix} 
        1 & 2 & 3 \\ 4 & 2 & 1 \\ 6 & 2 & 0 
    \end{pmatrix} 
    \quad \text{and} \quad 
    \mathbf{N} = \begin{pmatrix} 
        0 & 3 & 1 \\ 1 & 1 & 4 \\ 2 & 0 & 3 
    \end{pmatrix}
\end{align}

In [32]:
M = np.array([[1,2,3],[4,2,1],[6,2,0]])
N = np.array([[0,3,1],[1,1,4],[2,0,3]])

You can use Numpy to perform all kind of **Linear Algebra** operations on these matrices. Such as:

In [33]:
np.transpose(M)                    # reverse the Matrix M

array([[1, 4, 6],
       [2, 2, 2],
       [3, 1, 0]])

In [34]:
np.dot(M,N)                        # Calculate the dot product of M and N

array([[ 8,  5, 18],
       [ 4, 14, 15],
       [ 2, 20, 14]])

In [35]:
np.linalg.inv(M)                   # matrix inverse

array([[ 1. , -3. ,  2. ],
       [-3. ,  9. , -5.5],
       [ 2. , -5. ,  3. ]])

In [36]:
np.eye(3)                          # identity matrix

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [37]:
np.reshape(M,9)                    # reshape the matrix to a 1D row

array([1, 2, 3, 4, 2, 1, 6, 2, 0])

In [38]:
arr = np.reshape(range(9),(3,3))   # reshape the 1D row (range(9)) to a 3x3 matrix
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [39]:
np.delete(arr, 0, 1)                # remove the first column of the matrix

array([[1, 2],
       [4, 5],
       [7, 8]])

In [40]:
np.delete(arr, 2, 0)                # remove the third row of the matrix

array([[0, 1, 2],
       [3, 4, 5]])

#### Exercise 2

Write a function that calculates the dot product between two vectors: A · B = $\sum_{i} a_ib_i$. Find the between  first row of matrix `M` and the first column of matrix `N`.  

In [41]:
def my_dot(a,b):
    assert len(a)==len(b), "Arrays are of different sizes!"
    return sum([a[i]*b[i] for i in range(len(a))])

In [42]:
row = M[0]          #copies the first row from Matric M
column = N[:,0]     #copies the first column from Matric N
print(my_dot(row,column))

8


#### Exercise 3
Write a short script to compare:
1. M * N and np.dot(M, N)
2. N * M and np.dot(N, M)
3. M * M and M**2 and np.dot(M, M)

In [43]:
print("M*N",M*N)
print("M.N",np.dot(M,N))
print("N*M",N*M)
print("N.M",np.dot(N,M))
print("M*M",M*M)
print("M**2",M**2)
print("M.M",np.dot(M,M))

M*N [[ 0  6  3]
 [ 4  2  4]
 [12  0  0]]
M.N [[ 8  5 18]
 [ 4 14 15]
 [ 2 20 14]]
N*M [[ 0  6  3]
 [ 4  2  4]
 [12  0  0]]
N.M [[18  8  3]
 [29 12  4]
 [20 10  6]]
M*M [[ 1  4  9]
 [16  4  1]
 [36  4  0]]
M**2 [[ 1  4  9]
 [16  4  1]
 [36  4  0]]
M.M [[27 12  5]
 [18 14 14]
 [14 16 20]]


You can probably see that the multiplication (and exponentiation) operation happens element-wise, namely:
$MN[i][j] = M[i][j] * N[i][j]$

This is actually convenient in certain contexts, but is certainly not how we typically wish to multiply matrices!

#### Exercise 4
Consider the matrix **T1** as
\begin{align}
    \mathbf{T1} = \begin{pmatrix} 
        1 & 2 & 3 \\ 4 & 5 & 6 
    \end{pmatrix} 
\end{align}
and arrays T2 & T3 as **T2** = `<7, 8, 9>` **T3** = `<10, 20, 30>`. Right a script to do the following:
(a) add **T2** as the third row to **T1**; 
(b) add **T3** as the forth column to the result matrix

In [44]:
T1 = np.reshape(range(1,7), (2,3))
T2 = np.array([range(7,10)])
T3 = np.array([[10 , 20, 30]])

R1 = np.concatenate((T1, T2), axis=0)
print("R1",R1)

R2 = np.concatenate((R1, T3.T), axis=1)
print("R2",R2)

R1 [[1 2 3]
 [4 5 6]
 [7 8 9]]
R2 [[ 1  2  3 10]
 [ 4  5  6 20]
 [ 7  8  9 30]]


## Getting Help
Confused about a particular function / method? Putting a question mark `<?>` after the object in question will return the docstring.

In [45]:
np.random.normal?

## Interrupting/restarting the kernel

Code is run in the kernel process. You can interrupt the kernel by pressing the stop button <button class='btn btn-default btn-xs'><i class='icon-stop fa fa-stop'></i></button> in the toolbar. Try it out below.

In [46]:
import time
time.sleep(10)

Occassionally you may want to restart the kernel (e.g. to clear the namespace). You can do this by pressing the <button class='btn btn-default btn-xs'><i class='icon-epeat fa fa-repeat'></i></button> button in the toolbar. You can find more options under the _Kernel_ menu.